language: php

php:
  - 7.1
  - 7.2

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit

env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true
